#!/usr/bin/env bash
# cont-init 02 — (re)generate /opt/data/config.yaml and /opt/data/.env
# from the Space Variables/Secrets (or, on a plain VM, from the container
# environment) at EVERY boot, so changing a variable + restarting is
# enough to reconfigure everything.
set -u

H=/opt/data
mkdir -p "$H"

# ------------------------------------------------ default provider
# 'ninerouter' is only usable once you have created an API key by hand in
# the 9Router dashboard. OmniRouter is keyless, so it is the sane default
# whenever no 9Router key is present — that way a fresh install works with
# zero extra configuration.
if [ -n "${HERMES_PROVIDER:-}" ]; then
    DEFAULT_PROVIDER="$HERMES_PROVIDER"
elif [ -n "${NINEROUTER_API_KEY:-}" ]; then
    DEFAULT_PROVIDER="ninerouter"
else
    DEFAULT_PROVIDER="omnirouter"
fi

# ------------------------------------------------ default model
# NEVER fall back to a placeholder string: a model id that cannot resolve
# makes the bot connect and then fail on every single reply.
# OmniRouter's "auto" picks the healthiest keyless provider with automatic
# failover, so it is the safest zero-config default.
MODEL_ID="${HERMES_MODEL:-auto}"
WEB_BACKEND="${HERMES_WEB_BACKEND:-tavily}"

# ------------------------------------------------ OmniRouter key
# The router and the agent must share one key. Generate it once and keep it
# in /opt/data so it is stable across restarts.
KEY_FILE="$H/.omni_key"
if [ -z "${OMNI_ROUTER_KEY:-}" ]; then
    if [ ! -s "$KEY_FILE" ]; then
        printf 'sk-omni-%s' "$(tr -dc 'a-f0-9' < /dev/urandom | head -c 32)" > "$KEY_FILE"
        chmod 600 "$KEY_FILE"
    fi
    OMNI_ROUTER_KEY="$(cat "$KEY_FILE")"
fi

# ------------------------------------------------ config.yaml
cat > "$H/config.yaml" <<EOF
# ==== auto-generated by the kit (rebuilt at every boot) ====
model:
  provider: ${DEFAULT_PROVIDER}
  default: "${MODEL_ID}"

providers:
  # 9Router — free/paid models you connect in its dashboard (Kiro, OpenCode Free, ...)
  ninerouter:
    api: http://127.0.0.1:20128/v1
    key_env: NINEROUTER_API_KEY
    transport: chat_completions
    discover_models: true

  # OmniRouter — keyless web models (Qwen / Gemini / OpenCode guest)
  omnirouter:
    api: http://127.0.0.1:8080/v1
    key_env: OMNI_ROUTER_KEY
    transport: chat_completions
    discover_models: true

web:
  backend: ${WEB_BACKEND}
  keyless_fallback: true
  keyless_rescue: true
EOF

# ------------------------------------------------ .env
DASH=0
if [ -n "${DASHBOARD_USERNAME:-}" ] && [ -n "${DASHBOARD_PASSWORD:-}" ]; then
    DASH=1
fi

# stable session secret for the dashboard (persists in /opt/data)
if [ ! -f "$H/.dash_secret" ]; then
    tr -dc 'a-f0-9' < /dev/urandom | head -c 64 > "$H/.dash_secret"
fi
DASH_SECRET="$(cat "$H/.dash_secret")"

# Public base URL. On a Hugging Face Space $SPACE_HOST is injected for us;
# on a plain VM set PUBLIC_URL (e.g. http://203.0.113.10:7860) instead.
PUBLIC_BASE="${PUBLIC_URL:-}"
if [ -z "$PUBLIC_BASE" ]; then
    if [ -n "${SPACE_HOST:-}" ]; then
        PUBLIC_BASE="https://${SPACE_HOST}"
    else
        PUBLIC_BASE="http://localhost:${PUBLIC_PORT:-7860}"
    fi
fi

{
  echo "# ==== auto-generated by the kit (rebuilt at every boot) ===="
  if [ -n "${TELEGRAM_BOT_TOKEN:-}" ]; then
    echo "TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}"
  else
    echo "# TELEGRAM_BOT_TOKEN not set - the Telegram gateway will stay silent."
  fi
  if [ -n "${TELEGRAM_ALLOWED_USERS:-}" ]; then
    echo "TELEGRAM_ALLOWED_USERS=${TELEGRAM_ALLOWED_USERS}"
  else
    echo "# TELEGRAM_ALLOWED_USERS not set - Hermes denies ALL users by default."
  fi
  echo "HERMES_TIMEZONE=${HERMES_TIMEZONE:-UTC}"

  # ---- web-to-api: OpenAI-compatible API server on 8642 ----
  if [ -n "${HERMES_API_KEY:-}" ]; then
    echo "API_SERVER_ENABLED=true"
    echo "API_SERVER_KEY=${HERMES_API_KEY}"
    echo "API_SERVER_HOST=127.0.0.1"
    echo "API_SERVER_PORT=8642"
  else
    echo "API_SERVER_ENABLED=false"
  fi

  # ---- web dashboard on 9119 (behind Caddy at /hermes/) ----
  if [ "$DASH" = "1" ]; then
    echo "HERMES_DASHBOARD=1"
    echo "HERMES_DASHBOARD_PORT=9119"
    echo "HERMES_DASHBOARD_HOST=127.0.0.1"
    echo "HERMES_DASHBOARD_BASIC_AUTH_USERNAME=${DASHBOARD_USERNAME}"
    echo "HERMES_DASHBOARD_BASIC_AUTH_PASSWORD=${DASHBOARD_PASSWORD}"
    echo "HERMES_DASHBOARD_BASIC_AUTH_SECRET=${DASH_SECRET}"
    echo "HERMES_DASHBOARD_PUBLIC_URL=${PUBLIC_BASE}/hermes/"
  else
    echo "HERMES_DASHBOARD=0"
  fi

  # ---- provider keys for config.yaml providers ----
  if [ -n "${NINEROUTER_API_KEY:-}" ]; then
    echo "NINEROUTER_API_KEY=${NINEROUTER_API_KEY}"
  fi
  # Always written: generated above when the operator did not supply one.
  echo "OMNI_ROUTER_KEY=${OMNI_ROUTER_KEY}"
} > "$H/.env"
chmod 600 "$H/.env"

echo "[write-config] config.yaml + .env written (provider=${DEFAULT_PROVIDER}, model=${MODEL_ID}, dashboard=${DASH})."
if [ -z "${TELEGRAM_BOT_TOKEN:-}" ]; then
    echo "[write-config] WARNING: TELEGRAM_BOT_TOKEN is empty - the bot cannot answer anyone."
fi
exit 0
